#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# DRIMS Creative HQ — local skill installer
#
# Run from inside a checkout of the drims-creative-hq repo:
#
#   cd path/to/drims-creative-hq
#   bash skills/install-skill.sh
#
# Installs:
#   • ffmpeg + yt-dlp (Homebrew)
#   • psycopg2-binary + requests + playwright (pip, --user)
#   • Playwright Chromium
#   • Both skill folders under ~/.claude/skills/
#         classify-inspiration/     (SKILL.md + fb_ad_classifier.py)
#         clickup-creative-pipeline/ (SKILL.md)
#   • Env file at ~/.drims-classify.env (chmod 600) — prompts if missing
#
# Re-running is safe: dependencies are skipped if already present,
# skill files are overwritten with the repo's current versions, and
# the env file is left alone unless you pass --reset-env.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

INSTALLER_VERSION="1.0.0-drims"
SKILL_ROOT_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_ROOT_DST="$HOME/.claude/skills"
ENV_FILE="$HOME/.drims-classify.env"

RESET_ENV=0
for arg in "$@"; do
  case "$arg" in
    --reset-env) RESET_ENV=1 ;;
    -h|--help)
      sed -n '2,22p' "$0"
      exit 0
      ;;
  esac
done

# Colors
BOLD=$'\e[1m'; RED=$'\e[31m'; GRN=$'\e[32m'; YLW=$'\e[33m'; BLU=$'\e[36m'; OFF=$'\e[0m'
say()   { echo "${BLU}▸${OFF} $*"; }
ok()    { echo "${GRN}✓${OFF} $*"; }
warn()  { echo "${YLW}⚠${OFF} $*"; }
fail()  { echo "${RED}✗${OFF} $*"; exit 1; }

echo ""
echo "${BOLD}DRIMS Creative HQ — skill installer v${INSTALLER_VERSION}${OFF}"
echo ""
echo "This will install ~200 MB of dependencies (ffmpeg, Playwright Chromium)"
echo "and set up your Supabase + ClickUp credentials."
echo ""

# ── 0. Sanity checks ───────────────────────────────────────────────────────
if [[ "$(uname -s)" != "Darwin" ]]; then
  fail "This installer is macOS-only. You're on $(uname -s)."
fi
if ! command -v brew >/dev/null 2>&1; then
  fail "Homebrew not installed. Install it from https://brew.sh and re-run."
fi
if ! command -v python3 >/dev/null 2>&1; then
  fail "python3 not on PATH. Install via: brew install python@3.12"
fi
if ! command -v claude >/dev/null 2>&1; then
  warn "Claude Code CLI not detected. Install it before the skills can be used."
fi

# Confirm we're being run from inside the repo (sanity — skills folder should exist)
if [[ ! -d "$SKILL_ROOT_SRC/classify-inspiration" || ! -d "$SKILL_ROOT_SRC/clickup-creative-pipeline" ]]; then
  fail "Can't find skill folders next to this script. Run from inside the drims-creative-hq checkout:  bash skills/install-skill.sh"
fi

# ── 1. Credentials ──────────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" && "$RESET_ENV" -eq 0 ]]; then
  ok "Env file already exists at $ENV_FILE (use --reset-env to overwrite)"
else
  echo "${BOLD}Step 1 — Credentials${OFF}"
  echo "Paste the following from your Supabase + ClickUp dashboards."
  echo "(Input is hidden for secret values — that's normal.)"
  echo ""

  read -rp  "  SUPABASE_URL (e.g. https://abcd1234.supabase.co): " SUPABASE_URL
  read -rsp "  SUPABASE_SERVICE_ROLE_KEY (bypasses RLS, keep secret): " SUPABASE_SERVICE_ROLE_KEY; echo ""
  read -rsp "  SUPABASE_DB_PASSWORD: " SUPABASE_DB_PASSWORD; echo ""
  read -rp  "  CLICKUP_API_KEY (pk_... from ClickUp \xe2\x86\x92 Apps): " CLICKUP_API_KEY
  read -rp  "  CLICKUP_WORKSPACE_ID (from ClickUp URL): " CLICKUP_WORKSPACE_ID
  read -rp  "  CLICKUP_INSPIRATION_FOLDER_ID (folder for briefs): " CLICKUP_INSPIRATION_FOLDER_ID
  read -rp  "  CLICKUP_SPACE_ID (parent space of the folder, optional): " CLICKUP_SPACE_ID || true
  echo ""

  # Extract host from SUPABASE_URL for SUPABASE_DB_URL construction
  SB_HOST_RAW="${SUPABASE_URL#https://}"
  SB_HOST_RAW="${SB_HOST_RAW#http://}"
  SB_HOST_RAW="${SB_HOST_RAW%/}"
  SB_HOST="db.${SB_HOST_RAW}"

  cat > "$ENV_FILE" <<ENVEOF
# DRIMS Creative HQ — local skill credentials. DO NOT COMMIT or share.
# Generated by skills/install-skill.sh v${INSTALLER_VERSION} at $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Supabase
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
SUPABASE_DB_URL=postgresql://postgres:${SUPABASE_DB_PASSWORD}@${SB_HOST}:5432/postgres
SUPABASE_HOST=${SB_HOST_RAW}
#
# ClickUp
CLICKUP_API_KEY=${CLICKUP_API_KEY}
CLICKUP_WORKSPACE_ID=${CLICKUP_WORKSPACE_ID}
CLICKUP_INSPIRATION_FOLDER_ID=${CLICKUP_INSPIRATION_FOLDER_ID}
CLICKUP_SPACE_ID=${CLICKUP_SPACE_ID}
ENVEOF
  chmod 600 "$ENV_FILE"
  ok "Env file written (chmod 600, readable only by you)"
fi

# ── 2. System binaries ─────────────────────────────────────────────────────
say "Installing ffmpeg + yt-dlp via Homebrew (skipping if present)"
brew list ffmpeg >/dev/null 2>&1 || brew install ffmpeg >/dev/null
brew list yt-dlp >/dev/null 2>&1 || brew install yt-dlp >/dev/null
ok "ffmpeg $(ffmpeg -version | head -1 | awk '{print $3}'), yt-dlp $(yt-dlp --version)"

# ── 3. Python packages ─────────────────────────────────────────────────────
say "Installing Python packages (psycopg2-binary, requests, playwright)"
pip3 install -q --user --break-system-packages psycopg2-binary requests playwright 2>/dev/null \
  || pip3 install -q --user psycopg2-binary requests playwright
ok "Python packages installed"

# ── 4. Playwright Chromium ─────────────────────────────────────────────────
say "Installing Playwright Chromium (skipped if already present)"
python3 -m playwright install chromium >/dev/null 2>&1 || {
  warn "Playwright chromium install returned non-zero. Trying again with visible output…"
  python3 -m playwright install chromium
}
ok "Playwright Chromium ready"

# ── 5. Copy skill folders into ~/.claude/skills/ ───────────────────────────
say "Installing skill files to $SKILL_ROOT_DST"
mkdir -p "$SKILL_ROOT_DST/classify-inspiration"
mkdir -p "$SKILL_ROOT_DST/clickup-creative-pipeline"
cp -f "$SKILL_ROOT_SRC/classify-inspiration/SKILL.md"            "$SKILL_ROOT_DST/classify-inspiration/SKILL.md"
cp -f "$SKILL_ROOT_SRC/classify-inspiration/fb_ad_classifier.py" "$SKILL_ROOT_DST/classify-inspiration/fb_ad_classifier.py"
cp -f "$SKILL_ROOT_SRC/clickup-creative-pipeline/SKILL.md"       "$SKILL_ROOT_DST/clickup-creative-pipeline/SKILL.md"
ok "Skill files installed"

# ── 6. Smoke test — Supabase connection ────────────────────────────────────
say "Smoke-testing Supabase connection"
set -a; source "$ENV_FILE"; set +a
SMOKE_OUT=$(python3 - <<PYEOF 2>&1
import os, sys
try:
    import psycopg2
    conn = psycopg2.connect(os.environ["SUPABASE_DB_URL"], connect_timeout=10)
    cur = conn.cursor(); cur.execute("select count(*) from public.products")
    count = cur.fetchone()[0]
    cur.close(); conn.close()
    print(f"OK {count}")
except Exception as e:
    print(f"FAIL {e}")
    sys.exit(1)
PYEOF
) || true

if [[ "$SMOKE_OUT" == OK* ]]; then
  PRODUCTS_COUNT="${SMOKE_OUT#OK }"
  ok "Connected — $PRODUCTS_COUNT product(s) in public.products"
else
  warn "Supabase smoke test failed: $SMOKE_OUT"
  warn "Check $ENV_FILE — if the schema.sql hasn't been run yet, that's expected."
fi

# ── Done ───────────────────────────────────────────────────────────────────
echo ""
echo "${BOLD}${GRN}Installation complete${OFF}"
echo ""
echo "Next:"
echo "  1. Open Claude Code in any terminal"
echo "  2. Type ${BOLD}/classify-inspiration${OFF} — picks up URLs queued from the dashboard"
echo "     Or     ${BOLD}/clickup-creative-pipeline${OFF} — runs over a ClickUp list"
echo ""
echo "To update later:"
echo "  cd $SKILL_ROOT_SRC/.. && git pull && bash skills/install-skill.sh"
echo ""
echo "To uninstall:"
echo "  rm -rf $SKILL_ROOT_DST/classify-inspiration $SKILL_ROOT_DST/clickup-creative-pipeline $ENV_FILE"
echo ""
